spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneyj?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: moneyj
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: Asia/Seoul
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug
